Update user
Mikhail2506/michael-training pull request #1
Opened 2024-04-27 20:02 UTC by Mikhail2506

update_user method

2024-04-28 15:54 UTC, aliaksei-ivanouski requested changes

2024-04-28 15:54 UTC, aliaksei-ivanouski commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +            System.out.println(e.getMessage());
Зачем тут System.out.println(e.getMessage()) ?
Логика будет работать так:
- в случае отсутствия в базе user с данным id выбросится исключение NotFoundException
- блок catch его отловит и распечатает в консоли сообщение

Так не должно работать
Это сообщение должно появится в ответе клиенту и в логах

2024-04-28 15:54 UTC, aliaksei-ivanouski commented on docker-compose.local.yml
> +    build: "."
Объясни пожалуйста, как влияют данные изменения на функционал?

2024-04-28 15:54 UTC, aliaksei-ivanouski commented on src/main/java/com/example/michaeltraining/exception/ExceptionHandler.java
> +        userError.setInfo(exception.getMessage());
Запутанное название.
Мы сетаем exception message в поле info.
Почему бы не оставить тоже название message?

2024-04-28 15:54 UTC, aliaksei-ivanouski commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +import javassist.NotFoundException;
Надо найти исключение с таким же названием, но в другом пакете, либо создать свой, но сделать его наследником RuntimeException.

Почитай пожалуйста разницу между Throwable, Error, Exception (Checked Exception), RuntimeException (Unchecked Exception)

2024-04-28 20:18 UTC, Mikhail2506 commented
update_user изменения

2024-04-28 20:52 UTC, Mikhail2506 commented
измененный update_user

2024-04-30 18:20 UTC, Mikhail2506 commented
удалил ненужный pool request, в текущем сделал custom  exception, унаследовал его от Runtime, изменил источник импорта.

2024-05-01 10:40 UTC, aliaksei-ivanouski approved these changes
Approved!

2024-05-04 19:09 UTC, Mikhail2506 commented
update_user final version

2024-05-04 19:09 UTC, merged