Delete user
Mikhail2506/michael-training pull request #3
Opened 2024-05-05 18:44 UTC by Mikhail2506

delete_user method with custon exception

2024-05-09 03:34 UTC, Mikhail2506 commented
delete_user branch

2024-05-10 03:11 UTC, Mikhail2506 commented
delete_user

2024-05-10 03:31 UTC, Mikhail2506 commented
pull

2024-05-14 19:54 UTC, Mikhail2506 commented
delete-user

2024-05-15 09:28 UTC, aliaksei-ivanouski requested changes

2024-05-15 09:28 UTC, aliaksei-ivanouski commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +        if (userRepository.existsById(id)) {
А что будет если удалить сразу несуществующего user, без проверки на его наличие в базе?

2024-05-15 18:32 UTC, Mikhail2506 commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +        if (userRepository.existsById(id)) {
Удалит несуществующего!

2024-05-16 04:59 UTC, aliaksei-ivanouski requested changes

2024-05-16 04:59 UTC, aliaksei-ivanouski commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +        if (userRepository.existsById(id)) {
Пробовал так сделать? Что значит удалит несуществующего?
Будет ли выброшен какой-либо exception или получишь ответ 200 и в базе ничего не произойдет.
Предположения тут не будут работать. Надо тестить разные варианты и видеть глазами ответ.
Можешь сюда вставить ответы этого endpoint?

2024-05-16 08:57 UTC, Mikhail2506 commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +        if (userRepository.existsById(id)) {
Ок. Протестирую еще раз и отпишусь! НО только вечером!

2024-05-16 19:20 UTC, Mikhail2506 commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +        if (userRepository.existsById(id)) {
Вот такой ответ на попытку удалить несущeствующего user{
  "timestamp": "2024-05-16T19:16:51.885+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.dao.EmptyResultDataAccessException",
  "message": "No class com.example.michaeltraining.user.User entity with id 12 exists!",
  "path": "/api/v1/users/12"
}.

2024-05-16 19:48 UTC, Mikhail2506 commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +        if (userRepository.existsById(id)) {
Я понимаю, что никакого конкретного исключения в этом случае не выбрасывается, к DAO мы вообще отношения здесь не имеем. Ошибка 500  – это стандартный ответ Spring на возникновение любого неизвестного исключения.

2024-05-17 03:42 UTC, Mikhail2506 commented
Алексей, мне тест для getUser метода сбрасывать? 
Метод deleteUser я еще в основную ветку  merge не делал.

2024-05-17 04:04 UTC, aliaksei-ivanouski requested changes

2024-05-17 04:04 UTC, aliaksei-ivanouski commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +        if (userRepository.existsById(id)) {
Ошибка 500 это не Spring, а общий http статут ответа, который говорит о внутренней ошибке сервера. 
А вот параметр message в ответе дает полное представление о том, что случилось. И эта информация очень хороша для разработчика, но не для конечного пользователя. 
У тебя же уже есть кастомный NotFoundException, вот вместо if else попробуй обернуть вызов удаления пользователя в try catch и выбросить это же исключение с тем же сообщением.
throw new NotFoundException("User with id = " + id + " doesn't exist in Database");

2024-05-17 20:03 UTC, Mikhail2506 commented
added try-catch for delete_user method.

2024-05-18 06:58 UTC, aliaksei-ivanouski requested changes

2024-05-18 06:58 UTC, aliaksei-ivanouski commented on src/main/java/com/example/michaeltraining/user/UserServiceImpl.java
> +    public void deleteUser(Long id) throws RuntimeException{
Я думаю, что в этом месте RuntimeException не нужен

2024-05-19 03:03 UTC, merged